# ===============================
# APPLICATION
# ===============================
spring.application.name=PRODUCT-SERVICE
server.port=8091

# ===============================
# DATABASE POSTGRESQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/product_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# DISABLE EUREKA FOR LOCAL TEST
# ===============================
eureka.client.enabled=false

# ===============================
# CONFIG SERVER OPTIONAL
# ===============================
spring.config.import=optional:configserver:http://localhost:8888

# ===============================
# ACTUATOR
# ===============================
management.endpoints.web.exposure.include=*