# ===============================
# APPLICATION
# ===============================
spring.application.name=SUPPLY-SERVICE
server.port=8093

# ===============================
# DATABASE POSTGRESQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/supply_db
spring.datasource.username=postgres
spring.datasource.password=1234

spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# DISABLE EUREKA (test local)
# ===============================
eureka.client.enabled=false

# ===============================
# CONFIG SERVER (optionnel)
# ===============================
spring.config.import=optional:configserver:http://localhost:8888

# ===============================
# FEIGN CLIENT URLs (TEST LOCAL)
# ===============================
services.product.url=http://localhost:8091
services.supplier.url=http://localhost:8092

# ===============================
# ACTUATOR
# ===============================
management.endpoints.web.exposure.include=*

spring.cloud.openfeign.httpclient.hc5.enabled=true